var tagMap = {
    "recycling:aerosol_cans": "Aerosols",
    "recycling:aluminium": "Aluminium",
    "recycling:batteries": "Batteries",
    "recycling:books": "Books",
    "recycling:cans": "Cans",
    "recycling:car_batteries": "Car batteries",
    "recycling:cardboard": "Cardboard",
    "recycling:cartons": "Cartons",
    "recycling:ceramics": "Ceramics",
    "recycling:clothes": "Clothes",
    "recycling:cooking_oil": "Cooking oil",
    "recycling:electrical_appliances": "Electrical appliances",
    "recycling:electrical_items": "Electrical items",
    "recycling:engine_oil": "Engine oil",
    "recycling:fluorescent_tubes": "Fluorescent tubes",
    "recycling:garden_waste": "Garden waste",
    "recycling:glass": "Glass",
    "recycling:glass_bottles": "Glass bottles",
    "recycling:hazardous_waste": "Hazardous waste",
    "recycling:magazines": "Magazines",
    "recycling:newspaper": "Newspapers",
    "recycling:paint": "Paint",
    "recycling:paper": "Paper",
    "recycling:paper_packaging": "Paper packaging",
    "recycling:plasterboard": "Plasterboard",
    "recycling:plastic_bottles": "Plastic bottles",
    "recycling:scrap_metal": "Scrap metal",
    "recycling:small_appliances": "Small appliances",
    "recycling:tyres": "Tyres",
    "recycling:white_goods": "White goods",
    "recycling:wood": "Wood"
}